### ISSUE TITLE
Element height issue in many Arches Designer Pages

### ISSUE THREAD

**Issue by mradamcox** [archesproject/arches#1654]
### User Story
The bottom of panels that are longer/taller than the view window are obscured in Arches Designer pages
![image](https://cloud.githubusercontent.com/assets/10427268/23137864/1c28d5d2-f76a-11e6-96e9-fe409c4d78d4.png)
This is not noticeable if the panels are shorter than the view window.

I believe [this div](https://github.com/archesproject/arches/blob/master/arches/app/templates/views/graph/graph-base.htm#L55) is the culprit, and its height should be properly controlled.

#### Definition of Done
All contents should be fully visible in Arches Designer tool pages.

#### Your Arches Information
This is from Chrome on Windows 10.

**Comment by dwuthrich** [comment]
@mradamcox  This issue should be addressed in a recent UI enhancement PR.

**Comment by mradamcox** [comment]
Just pulled and rebuilt with master. Looks like, in the case of the card designer at least, this has been addressed in the contents panel but not the other panels. See screenshot. Do you see something different?
![image](https://cloud.githubusercontent.com/assets/10427268/23494332/de746b82-fed7-11e6-8837-79978aeb07a2.png)

This is a ticket for all of the designer pages that have this issue.

**Comment by dwuthrich** [comment]
@mradamcox Thanks for checking.  I'll take a closer look at this

**Comment by mradamcox** [comment]
I'd like to give a bump to this issue, because (and this may depend on screen size) it makes some components unusable (or at least contributes to the issue), as illustrated below. You can't see anything but the top entry in the list of collections.
![image](https://cloud.githubusercontent.com/assets/10427268/24103949/e41e70f2-0d4e-11e7-909c-a0a989610c0c.png)

**Comment by mradamcox** [comment]
I didn't check all of the pages, but there's still a problem with the graph designer, at least.

![image](https://cloud.githubusercontent.com/assets/10427268/25247862/c3f3381c-25d1-11e7-9661-22ec45b65a2c.png)

**Comment by chiatt** [comment]
@mradamcox Added a fix for the center panel height. It should be okay now. Can you confirm?

**Comment by mradamcox** [comment]
Looks good. It also fixes a similar issue I was seeing in the main Search page. It seems to reveal that the map is larger than its container, which creates both x and y scroll bars for me with Chrome on Windows at least. Anyway, closing this ticket, all good.
